admincontrollers:
    resource: "../src/Controller/Admin/"
    type:     annotation
    prefix:   /
    defaults:  { _locale: '%locale%' }
    requirements:
        _locale: fr|en

controllers:
    resource: "../src/Controller/"
    type:     annotation
    prefix:   /
    defaults:  { _locale: '%locale%' }
    requirements:
        _locale: fr|en

login:
    path:  /connexion
    defaults: { _controller: App\Controller\GlobalController::connexion, _locale: '%locale%' }
    requirements:
        _locale: fr|en



home:
    path: /
    defaults: { _controller: App\Controller\GlobalController::accueil, _locale: '%locale%' }
    requirements:
        _locale: fr|en